force-app/main/default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Account</relationshipLabel>
    <relationshipName>Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reference__c/Reference__c.object-meta.xml
<CustomObject>
    <label>Reference</label>
    <nameField>
        <displayFormat>Ref-{0000}</displayFormat>
        <label>Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reference__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>References</relationshipLabel>
    <relationshipName>References</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reference__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>References</relationshipLabel>
    <relationshipName>References</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Territory</relationshipLabel>
    <relationshipName>Territory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TerritoryUser__c/TerritoryUser__c.object-meta.xml
<CustomObject>
    <label>TerritoryUser</label>
    <nameField>
        <displayFormat>TER-USER-{0000}</displayFormat>
        <label>TerritoryUser Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TerritoryUsers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TerritoryUser__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>TerritoryUsers</relationshipLabel>
    <relationshipName>TerritoryUsers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TerritoryUser__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TerritoryUsers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountHelper.cls
public with sharing class AccountHelper {

	public static List<AccountShare> getAccountSharesByAccountAndTerritories(Map<Id, Set<Territory__c>> accountWithTerritories) {
		List<AccountShare> result = new List<AccountShare>();

		for (Id accountId : accountWithTerritories.keySet()) {
			for (Territory__c territories : accountWithTerritories.get(accountId)) {
				if (territories.TerritoryUsers__r != null) {
					for (TerritoryUser__c TerritoryUser : territories.TerritoryUsers__r) {
						if(TerritoryUser.User__c != null) {
							result.add(AccountShareHelper.createAccountShareByUserAndAccount(TerritoryUser.User__c, accountId));
						}
					}
				}
			}
		}

		return result;
	}


	public static void deleteOldAccountContactShares(Map<Id,Account > oldAccounts){
		List<AccountShare> accountShare = new List<AccountShare>();

		accountShare = AccountHelper.getAccountSharesByAccount(oldAccounts.values());

		if(!accountShare.isEmpty()){
			delete accountShare;
		}

		AccountHandler.deleteContactSharesByAccounts(oldAccounts.values());
	}

	public static List<AccountShare> getAccountSharesByAccount(List<Account> accounts) {
		return [SELECT Id
				FROM AccountShare
				WHERE AccountId IN :accounts
		    	AND RowCause = 'Manual'
		];
	}

	public static Map<Id, Set<Id>> getAccountsWithUsersByAccounts(Set<Id> accountsId) {
		Map<Id, Set<Id>> result = new Map<Id, Set<Id>>();

		List<AccountShare> accountShares= [SELECT Id,
		 											AccountId,
		 											UserOrGroupId
		 									FROM AccountShare
		 									WHERE AccountId IN : accountsId
											AND RowCause = 'Manual'
		];

		for(AccountShare elem: accountShares){
			if(result.containsKey(elem.AccountId)){
				result.get(elem.AccountId).add(elem.UserOrGroupId);
			}else{
				result.put(elem.AccountId, new Set<Id>{elem.UserOrGroupId});
			}
		}

		return result;
	}

	public static List<Account> getAccountsByTerritories(Set<Id> territoriesId) {
		return [SELECT Id,
						Name,
			   (SELECT Id, Contact__c FROM References__r)
				FROM Account
				WHERE Territory__c IN :territoriesId
		];
	}

	public static List<AccountShare> getAccountSharesByUsersAndAccounts(Map<Id, List<Account>> territoryWithAccounts,
																		  			Map<Id, Set<Id>> territoryIdWithUsersId) {
		List<AccountShare> result = new List<AccountShare>();
		List<AccountShare> accountShares = new List<AccountShare>();

		for(Id territoryId: territoryWithAccounts.keySet()){
			if(territoryIdWithUsersId.containsKey(territoryId)){
				accountShares = getSharesByUsersIdAndAccount(territoryWithAccounts.get(territoryId),
																		territoryIdWithUsersId.get(territoryId));
				result.addAll(accountShares);
			}
		}

		return result;
	}

	private static List<AccountShare> getSharesByUsersIdAndAccount(List<Account> accounts, Set<Id> usersId) {
		return [SELECT Id
				FROM AccountShare
				WHERE AccountId IN :accounts
				AND UserOrGroupId IN :usersId
				AND RowCause = 'Manual'
		];
	}

	public static List<AccountShare> createAccountSharesByAccountAndUsersId(Map<Id, List<Account>> territoryWithAccounts,
																			Map<Id, Set<Id>> territoryIdWithUsersId) {
		List<AccountShare> result = new List<AccountShare>();
		List<AccountShare> accountShare = new List<AccountShare>();

		for(Id territoryId: territoryWithAccounts.keySet()){
			if(territoryIdWithUsersId.containsKey(territoryId) ) {
				accountShare = createAcccontactShares(territoryWithAccounts.get(territoryId),
						territoryIdWithUsersId.get(territoryId));
				result.addAll(accountShare);
			}
		}

		return result;
	}

	private static List<AccountShare> createAcccontactShares(List<Account> accounts, Set<Id> usersId) {
		List<AccountShare> result = new List<AccountShare>();

		for(Account account: accounts){
			for(Id userId: usersId){
				result.add(AccountShareHelper.createAccountShareByUserAndAccount(userId, account.Id));
			}
		}

		return result;
	}
}