force-app/main/default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Account</relationshipLabel>
    <relationshipName>Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reference__c/Reference__c.object-meta.xml
<CustomObject>
    <label>Reference</label>
    <nameField>
        <displayFormat>Ref-{0000}</displayFormat>
        <label>Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reference__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>References</relationshipLabel>
    <relationshipName>References</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reference__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>References</relationshipLabel>
    <relationshipName>References</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Territory</relationshipLabel>
    <relationshipName>Territory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TerritoryUser__c/TerritoryUser__c.object-meta.xml
<CustomObject>
    <label>TerritoryUser</label>
    <nameField>
        <displayFormat>TER-USER-{0000}</displayFormat>
        <label>TerritoryUser Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TerritoryUsers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TerritoryUser__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>TerritoryUsers</relationshipLabel>
    <relationshipName>TerritoryUsers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TerritoryUser__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TerritoryUsers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TerritoryUserHandler.cls
public with sharing class TerritoryUserHandler {

	public static void insertNewAccAndContactShares(List<TerritoryUser__c> newTerritoryUser) {
		List<AccountShare> accountsShares = new List<AccountShare>();
		List<ContactShare> contactsShares = new List<ContactShare>();
		Map<Id, Set<Id>> usersIdWithTerritoryIncludeChild = new Map<Id, Set<Id>>();
		for (TerritoryUser__c TerritoryUser : newTerritoryUser) {
			if (usersIdWithTerritoryIncludeChild.containsKey(TerritoryUser.User__c)) {
				usersIdWithTerritoryIncludeChild.get(TerritoryUser.User__c).add(TerritoryUser.Territory__c);
			} else {
				if (TerritoryUser.User__c != null) {
					usersIdWithTerritoryIncludeChild.put(TerritoryUser.User__c, new Set<Id>{TerritoryUser.Territory__c});
				}
			}

			for (Id userId : usersIdWithTerritoryIncludeChild.keySet()) {
				Set<Id> territoriesIdIncludeChild = new Set<Id>();
				territoriesIdIncludeChild =	TerritoryHelper.getTerritoriesWithChildByTerritoriesId(usersIdWithTerritoryIncludeChild.get(userId));
				usersIdWithTerritoryIncludeChild.put(userId, territoriesIdIncludeChild);

				List<Account> accounts = ReferenceHelper.getAccountByTerritoriesId(usersIdWithTerritoryIncludeChild.get(userId));
				for (Account account : accounts) {
					accountsShares.add(AccountShareHelper.createAccountShareByUserAndAccount(userId, account.Id));
					contactsShares.addAll(ContactShareHelper.createContactsSharesByUsersAndReferences(userId, account.References__r));
				}

			}	
		}
		if (!accountsShares.isEmpty()) {
			insert accountsShares;
			if (!contactsShares.isEmpty()) {
				insert contactsShares;
			}
		}
	}
	public static void deleteOldAccountsAndContactsShares(List<TerritoryUser__c> oldTerritoryUser) {
		Set<Id> accountsIdByTerritory = new Set<Id>();
		Set<Id> contactsIdByAccount = new Set<Id>();
		Map<Id, Set<Id>> usersIdWithTerritoryIncludeChild = new Map<Id, Set<Id>>();

		for (TerritoryUser__c elem : oldTerritoryUser) {
			if (usersIdWithTerritoryIncludeChild.containsKey(elem.User__c)) {
				usersIdWithTerritoryIncludeChild.get(elem.User__c).add(elem.Territory__c);
			} else {
				usersIdWithTerritoryIncludeChild.put(elem.User__c, new Set<Id>{elem.Territory__c});
			}
			for (Id userId : usersIdWithTerritoryIncludeChild.keySet()) {
				Set<Id> territoriesIdIncludeChild = new Set<Id>();
				territoriesIdIncludeChild =
						TerritoryHelper.getTerritoriesWithChildByTerritoriesId(usersIdWithTerritoryIncludeChild.get(userId));
				System.debug(territoriesIdIncludeChild);

				usersIdWithTerritoryIncludeChild.put(userId, territoriesIdIncludeChild);

				List<Account> accountsByTerritory = ReferenceHelper.getAccountByTerritoriesId(usersIdWithTerritoryIncludeChild.get(userId));
				for (Account account: accountsByTerritory){
					accountsIdByTerritory.add(account.Id);
					for(Reference__c reference: account.References__r){
						contactsIdByAccount.add(reference.Contact__c);
					}
				}
			}
			AccountShareHelper.deleteAccountsSharesByUsersIdAndAccountsId(usersIdWithTerritoryIncludeChild.keySet(), accountsIdByTerritory);
			ContactShareHelper.deleteContactsSharesByUsersIdAndContactsId(usersIdWithTerritoryIncludeChild.keySet(), contactsIdByAccount);
		}
	}
}