force-app/main/default/objects/Account/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Account</relationshipLabel>
    <relationshipName>Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reference__c/Reference__c.object-meta.xml
<CustomObject>
    <label>Reference</label>
    <nameField>
        <displayFormat>Ref-{0000}</displayFormat>
        <label>Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Territory</relationshipLabel>
    <relationshipName>Territory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TerritoryUser__c/TerritoryUser__c.object-meta.xml
<CustomObject>
    <label>TerritoryUser</label>
    <nameField>
        <displayFormat>TER-USER-{0000}</displayFormat>
        <label>TerritoryUser Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TerritoryUsers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TerritoryUser__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>TerritoryUsers</relationshipLabel>
    <relationshipName>TerritoryUsers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TerritoryUser__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TerritoryUsers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountHandler.cls
public with sharing class AccountHandler {

	public static void insertAccountAndContactShares(List<Account> accounts) {
		List<AccountShare> accountShares = new List<AccountShare>();
		List<ContactShare> contactShare = new List<ContactShare>();
		List<Reference__c> accountReferences = new List<Reference__c>();
		Set<Id> accountsId = new Set<Id>();
		Map<Id, Set<Territory__c>> accountWithTerritories = new Map<Id, Set<Territory__c>>();

		for(Account acc: accounts){
			accountsId.add(acc.Id);
		}

		accountWithTerritories = TerritoryHelper.getTerritoriesWithParentsByAccount(accounts);
		accountShares = AccountHelper.getAccountSharesByAccountAndTerritories(accountWithTerritories);

		if (!accountShares.isEmpty()) {
			insert accountShares;
		}

		accountReferences = ReferenceHelper.getReferencesByAccounts(accountsId);

		for (Id accountId : accountWithTerritories.keySet()) {
			for (Territory__c territories : accountWithTerritories.get(accountId)) {
				if (territories.TerritoryUsers__r != null) {
					for (TerritoryUser__c TerritoryUser : territories.TerritoryUsers__r) {
						if(TerritoryUser.User__c != null) {
							contactShare.addAll(ContactShareHelper.createContactsSharesByUsersAndReferences(TerritoryUser.User__c, accountReferences));
						}
					}
				}
			}
		}

		if(!contactShare.isEmpty()){
			insert contactShare;
		}

	}

	public static void deleteContactSharesByAccounts(List<Account> accounts) {
		List<ContactShare> contactShares = new List<ContactShare>();
		Set<Id> contactsId = ContactHelper.getContactsByAccounts(accounts);

		contactShares = ContactShareHelper.getContactsSharesByContacts(contactsId);

		if(!contactShares.isEmpty()){
			delete contactShares;
		}
	}

	public static void deleteOldSharesAndInsertNewShares(List<Account> newAccounts, Map<Id, Account> oldAccounts) {
		Map<Id, Account> accountsWithNewTerritories = new Map<Id, Account>();
		Map<Id, Account> accountsWithOldTerritories = new Map<Id, Account>();

		for (Account account: newAccounts){
			if(account.Territory__c != oldAccounts.get(account.Id).Territory__c	){
				accountsWithOldTerritories.put(account.Id, account);
				if(account.Territory__c != null){
					accountsWithNewTerritories.put(account.Id, account);
				}
			}
		}
		if(!accountsWithOldTerritories.isEmpty()){
			AccountHelper.deleteOldAccountContactShares(accountsWithOldTerritories);
		}

		insertAccountAndContactShares(accountsWithNewTerritories.values());

	}
}