force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>Territory</relationshipLabel>
    <relationshipName>Territory</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TerritoryUser__c/TerritoryUser__c.object-meta.xml
<CustomObject>
    <label>TerritoryUser</label>
    <nameField>
        <displayFormat>TER-USER-{0000}</displayFormat>
        <label>TerritoryUser Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TerritoryUsers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TerritoryUser__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory</label>
    <referenceTo>Territory__c</referenceTo>
    <relationshipLabel>TerritoryUsers</relationshipLabel>
    <relationshipName>TerritoryUsers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TerritoryUser__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TerritoryUsers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TerritoryUserHelper.cls
public with sharing class TerritoryUserHelper {
	public static Map<Id, Set<Id>> getUsersByTerritory(Map<Id, Set<Territory__c>> territoryIdWithFathersTerritory) {
		Map<Id, Set<Id>> result = new Map<Id, Set<Id>>();
		Set<Id> usersId =new Set<Id>();
		for(Id idTerritory: territoryIdWithFathersTerritory.keySet()){
			usersId = getUsersByTerritories(territoryIdWithFathersTerritory.get(idTerritory));
			if(!usersId.isEmpty()){
				result.put(idTerritory, usersId);
			}
		}
		return result;
	}
	private static Set<Id> getUsersByTerritories(Set<Territory__c> territories) {
		Set<Id> usersId = new Set<Id>();
		Set<Id> territoriesId = new Set<Id>();
		for(Territory__c elem: territories){
			territoriesId.add(elem.Id);
		}
		List<TerritoryUser__c> TerritoryUsers= [SELECT Id,
							Territory__c,
							User__c
							FROM TerritoryUser__c
							WHERE Territory__c IN :territoriesId];
		for(TerritoryUser__c TerritoryUser: TerritoryUsers){
			if(TerritoryUser.User__c!=null){
				usersId.add(TerritoryUser.User__c);
			}
		}
		return usersId;
	}
}